package:
  name: processflow
  version: {{ environ['VERSION'] }}

source:
  git_url: git://github.com/ACME-Climate/acme_workflow
  git_tag: {{ environ['TAG'] }}
build:
  script: python setup.py install
  string: {{ environ['BUILD_NAME'] }}

requirements:
  build:
    - python
    - setuptools
  
  run:
    - peewee
    - acme_diags
    - markupsafe
    - matplotlib
    - nco
    - ncurses
    - pip
    - python
    - setuptools
    - sqlite
    - configobj
    - globus-sdk ==1.1.1
    - globus-cli ==1.1.2
    - jmespath
    - six
    - libcf
    - hdf5

about:
    home: https://github.com/ACME-Climate/acme_workflow
    summary: Automated post processing for E3SM model data
