package:
  name: processflow
  version: {{ environ['VERSION'] }}

source:
  git_url: git://github.com/ACME-Climate/acme_workflow

build:
  script: python setup.py install
  string: {{ environ['BUILD_NAME'] }}

requirements:
  build:
    - python
    - setuptools
  
  run:
    - peewee
    - acme_diags
    - alabaster
    - asn1crypto
    - astroid
    - autopep8
    - babel
    - backports.functools_lru_cache
    - backports.shutil_get_terminal_size
    - backports_abc
    - basemap
    - bkcharts
    - bleach
    - bokeh
    - bottleneck
    - bzip2
    - ca-certificates
    - cartopy
    - cdms2
    - cdtime
    - cdutil
    - certifi
    - cffi
    - chardet
    - clapack
    - click
    - cloudpickle
    - configparser
    - cryptography
    - curl
    - cycler
    - cyordereddict
    - dask
    - decorator
    - distarray
    - distributed
    - docutils
    - entrypoints
    - enum34
    - eofs
    - esmf
    - esmpy
    - expat
    - fastcache
    - ffmpeg
    - flake8
    - fontconfig
    - freetype
    - functools32
    - futures
    - g2clib
    - genutil
    - geos
    - gmp
    - gsl
    - h5netcdf
    - h5py
    - hdf4
    - hdf5
    - heapdict
    - html5lib
    - icu
    - idna
    - imagesize
    - ipaddress
    - ipykernel
    - ipython
    - ipython_genutils
    - ipywidgets
    - isort
    - jasper
    - jedi
    - jinja2
    - jpeg
    - jsonschema
    - jupyter
    - jupyter_client
    - jupyter_console
    - jupyter_core
    - lapack
    - lazy-object-proxy
    - libcdms
    - libcf
    - libdrs
    - libdrs_f
    - libffi
    - libiconv
    - libnetcdf
    - libpng
    - libsodium
    - libtiff
    - libxml2
    - libxslt
    - locket
    - lxml
    - markupsafe
    - matplotlib
    - mccabe
    - mistune
    - mpc
    - mpfr
    - mpich
    - mpmath
    - msgpack-python
    - nb_conda
    - nb_conda_kernels
    - nbconvert
    - nbformat
    - nco
    - ncurses
    - netcdf-fortran
    - netcdf4
    - notebook
    - numpydoc
    - olefile
    - openblas
    - openssl
    - ossuuid
    - owslib
    - pandas
    - pandoc
    - pandocfilters
    - partd
    - pathlib2
    - pep8
    - pexpect
    - pickleshare
    - pillow
    - pip
    - proj4
    - prompt_toolkit
    - psutil
    - ptyprocess
    - py
    - pycodestyle
    - pycparser
    - pyepsg
    - pyflakes
    - pygments
    - pylint
    - pyopenssl
    - pyparsing
    - pyproj
    - pyshp
    - pysocks
    - pyspharm
    - pytest
    - python
    - python-dateutil
    - pytz
    - pyyaml
    - pyzmq
    - qtawesome
    - qtconsole
    - qtpy
    - readline
    - requests
    - rope
    - scandir
    - setuptools
    - shapely
    - simplegeneric
    - singledispatch
    - six
    - snowballstemmer
    - sortedcontainers
    - sphinx
    - sphinxcontrib-websupport
    - spyder
    - sqlite
    - ssl_match_hostname
    - subprocess32
    - sympy
    - tblib
    - terminado
    - testpath
    - tk
    - toolz
    - tornado
    - traitlets
    - typing
    - udunits2
    - urllib3
    - wcwidth
    - webencodings
    - wheel
    - widgetsnbextension
    - windspharm
    - wrapt
    - x264
    - xarray
    - xz
    - yaml
    - zeromq
    - zict
    - zlib
    - cloog
    - gcc
    - isl
    - libgcc
    - libgfortran
    - mkl
    - numpy
    - pyqt
    - qt
    - scikit-learn
    - scipy
    - sip
    - asciidata
    - binaryio
    - cdp
    - cssgrid
    - dsgrid
    - dv3d
    - hdf5tools
    - lmoments
    - natgrid
    - ort
    - output_viewer
    - regridpack
    - shgrid
    - thermo
    - trends
    - uvcdat
    - uvcmetrics
    - vcsaddons
    - vistrails
    - vtk-cdat
    - wk
    - xmgrace
    - zonalmeans
    - cdat_info
    - vcs
    - configobj
    - globus-sdk
    - globus-cli
    - jmespath
    - mesalib

about:
    home: https://github.com/ACME-Climate/acme_workflow
    summary: Automated post processing for ACME model data
