#!/bin/bash
PASSED=0
TOTAL=11

echo "--- testing setup ---"
if COVERAGE_FILE=.coverage_setup coverage run --source=.,lib,jobs --omit="lib/test*","*__init__.py","setup.py" lib/test_setup.py; then
    echo "setup test passed"
    let "PASSED+=1"
else
    echo "setup test failed"
fi

echo "--- testing YearSet ---"
if COVERAGE_FILE=.coverage_yearset coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_yearset.py; then
    echo "YearSet test passed"
    let "PASSED+=1"
else
    echo "YearSet test failed"
fi

echo "--- testing FileManager ---"
if COVERAGE_FILE=.coverage_filemanager coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_filemanager.py; then
    echo "filemanager test passed"
    let "PASSED+=1"
else
    echo "filemanager test failed"
fi

echo "--- testing util ---"
if COVERAGE_FILE=.coverage_util coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_util.py; then
    echo "util test passed"
    let "PASSED+=1"
else
    echo "util test failed"
fi

echo "--- testing slurm ---"
if COVERAGE_FILE=.coverage_slurm coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_slurm.py; then
    echo "slurm test passed"
    let "PASSED+=1"
else
    echo "slurm test failed"
fi

echo "--- testing transfer ---"
if COVERAGE_FILE=.coverage_transfer coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" jobs/test_transfer.py; then
    echo "transfer test passed"
    let "PASSED+=1"
else
    echo "transfer test failed"
fi

echo "--- testing mailer ---"
if COVERAGE_FILE=.coverage_mailer coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_mailer.py; then
    echo "mailer test passed"
    let "PASSED+=1"
else
    echo "mailer test failed"
fi

echo "--- testing ncclimo ---"
if COVERAGE_FILE=.coverage_ncclimo coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" jobs/test_ncclimo.py; then
    echo "ncclimo test passed"
    let "PASSED+=1"
else
    echo "ncclimo test failed"
fi

echo "--- testing timeseries ---"
if COVERAGE_FILE=.coverage_timeseries coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" jobs/test_timeseries.py; then
    echo "timeseries test passed"
    let "PASSED+=1"
else
    echo "timeseries test failed"
fi

echo "--- testing amwg ---"
if COVERAGE_FILE=.coverage_amwg coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" jobs/test_amwg.py; then
    echo "amwg test passed"
    let "PASSED+=1"
else
    echo "amwg test failed"
fi

echo "--- testing runmanager ---"
if COVERAGE_FILE=.coverage_runmanager coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_runmanager.py; then
    echo "runmanager test passed"
    let "PASSED+=1"
else
    echo "runmanager test failed"
fi

coverage combine .coverage_runmanager .coverage_amwg .coverage_timeseries .coverage_ncclimo .coverage_mailer .coverage_transfer .coverage_setup .coverage_util .coverage_yearset .coverage_filemanager .coverage_slurm
coverage report
coverage html
coverage xml

if [ -d /var/www/acme/acme-diags/baldwin32/htmlcov ]; then
    rm -rf /var/www/acme/acme-diags/baldwin32/htmlcov
fi
mv htmlcov /var/www/acme/acme-diags/baldwin32
rm slurm-*

echo $PASSED "out of" $TOTAL "modules passed their tests"


if [ "$PASSED" != "$TOTAL" ]; then
    echo "One or more tests failed"
    exit 1
else
    echo "tests done"
    echo "report available at https://acme-viewer.llnl.gov/baldwin32/htmlcov/"
fi