#!/bin/bash
FAILED=false

echo "--- testing setup ---"
if COVERAGE_FILE=.coverage_setup coverage run --source=.,lib,jobs --omit="lib/test*","*__init__.py","setup.py" lib/test_setup.py; then
    echo "setup test passed"
else
    echo "setup test failed"
    FAILED=true
fi

echo "--- testing YearSet ---"
if COVERAGE_FILE=.coverage_yearset coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_yearset.py; then
    echo "YearSet test passed"
else
    echo "YearSet test failed"
    FAILED=true
fi

echo "--- testing FileManager ---"
if COVERAGE_FILE=.coverage_filemanager coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_filemanager.py; then
    echo "filemanager test passed"
else
    echo "filemanager test failed"
    FAILED=true
fi

echo "--- testing util ---"
if COVERAGE_FILE=.coverage_util coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_util.py; then
    echo "util test passed"
else
    echo "util test failed"
    FAILED=true
fi

echo "--- testing slurm ---"
if COVERAGE_FILE=.coverage_slurm coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" lib/test_slurm.py; then
    echo "slurm test passed"
else
    echo "slurm test failed"
    FAILED=true
fi

echo "--- testing transfer ---"
if COVERAGE_FILE=.coverage_transfer coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" jobs/test_transfer.py; then
    echo "transfer test passed"
else
    echo "transfer test failed"
    FAILED=true
fi

echo "--- testing mailer ---"
if COVERAGE_FILE=.coverage_mailer coverage run --source=.,lib,jobs  --omit="lib/test*","*__init__.py","setup.py" jobs/test_transfer.py; then
    echo "mailer test passed"
else
    echo "mailer test failed"
    FAILED=true
fi

coverage combine .coverage_mailer .coverage_transfer .coverage_setup .coverage_util .coverage_yearset .coverage_filemanager .coverage_slurm
coverage report
coverage html
coverage xml

if [ -d /var/www/acme/acme-diags/baldwin32/htmlcov ]; then
    rm -rf /var/www/acme/acme-diags/baldwin32/htmlcov
fi
mv htmlcov /var/www/acme/acme-diags/baldwin32
rm slurm-*

if [ "$FAILED" ]; then
    echo "One or more tests failed"
    exit 1
else
    echo "tests done"
    echo "report available at https://acme-viewer.llnl.gov/baldwin32/htmlcov/"
fi